Cnet:
  backend: Cnet_backend
  datapath: ~/.kaggle/competitions/ultrasound-nerve-segmentation/smalldataset
  optimizer: 'rmsprop'
  loss_function: 'binary_crossentropy'
  classes: 2
  epochs: 100
  batch_size: 1
  learn_rate: 0.01
  dropout: 0.5
  pretrained: True
  width: 256
  height: 256
  mask_width: 64
  mask_height: 64
  orig_width: 580
  orig_height: 420
  summarysteps: 10
  gray_img: True
  gray_mask: True
  metrices:
    - 'dice': 'protoseg.metrices.dice.dice'
    - 'jaccard': 'protoseg.metrices.jaccard.jaccard'
    - 'iou': 'protoseg.metrices.iou.iou'
