Cnet:
  backend: Cnet_backend
  datapath: ~/.kaggle/competitions/ultrasound-nerve-segmentation/smalldataset
  optimizer: 'rmsprop'
  loss_function: 'binary_crossentropy'
  classes: 2
  epochs: 10
  batch_size: 2
  learn_rate: 0.1
  dropout: 0.5
  pretrained: True
  width: 480
  height: 360
  orig_width: 580
  orig_height: 420
  summarysteps: 10
  color_img: True
  gray_mask: True
  metrices:
    - 'dice': 'protoseg.metrices.dice.dice'
    - 'jaccard': 'protoseg.metrices.jaccard.jaccard'
    - 'iou': 'protoseg.metrices.iou.iou'
