Cnet:
  backend: Cnet_backend
  datapath: ~/.kaggle/competitions/ultrasound-nerve-segmentation/fulldataset
  ignore_unlabeled: True
  optimizer: 'adadelta'
  loss_function: 'categorical_crossentropy'
  classes: 2
  epochs: 20
  batch_size: 4
  learn_rate: 0.001
  dropout: 0.5
  gate: 0.5
  pretrained: True
  width: 256
  height: 256
  mask_width: 128
  mask_height: 128
  orig_width: 580
  orig_height: 420
  summarysteps: 15
  gray_img: True
  gray_mask: True
  cnet_levels: 3
  cnet_depth: 2
  cnet_base_filter: 32
  shape_augmentation:
    - Multiply:
        mul: [0.75, 1.25]
    - Multiply:
        mul: [0.75, 1.25]
    - Affine:
        rotate: -15
    - Affine:
        rotate: 15
    - Affine:
        scale: [0.9, 3.0]
    - Fliplr:
        p: 1.0
  filters:
  # - 'Cnet.Filters.negative': []
  #  - 'Cnet.Filters.sharpen': []
  metrices:
    - 'dice': 'protoseg.metrices.dice.dice'
    - 'iou': 'protoseg.metrices.iou.iou'

  postprocessors:
    - 'Cnet.Postprocessors.argmax':
        background: 0.5

  hyperparamopt:
    - optimizer: ['adam', 'rmsprop']
    - loss_function: ['binary_crossentropy', 'mean_squared_error', 'dice_loss', 'categorical_hinge', 'dice_crossentropy']
    - mask_width: [64, 128, 256]
    - mask_height: [64, 128, 256]
    - cnet_levels: [2, 3]
    - cnet_depth: [2, 3, 4]
