Cnet:
  backend: Cnet_backend
  datapath: ~/.kaggle/competitions/ultrasound-nerve-segmentation
  ignore_unlabeled: True
  optimizer: 'adam'
  loss_function: 'dice_crossentropy'
  classes: 1
  epochs: 200
  batch_size: 2
  learn_rate: 0.01
  dropout: 0.0
  pretrained: True
  width: 256
  height: 256
  mask_width: 64
  mask_height: 64
  orig_width: 580
  orig_height: 420
  summarysteps: 25
  gray_img: True
  gray_mask: True
  cnet_levels: 3
  cnet_depth: 2
  cnet_base_filter: 32
  shape_augmentation:
    - Affine:
        rotate: -15
    - Affine:
        rotate: 15
    - Affine:
        rotate: -15
    - Affine:
        rotate: 15
    - Affine:
        scale: [0.8, 2.5]
    - Fliplr:
        p: 1.0
  filters:
    - 'Cnet.Filters.sharpen': []
  metrices:
    - 'dice': 'protoseg.metrices.dice.dice'
    - 'jaccard': 'protoseg.metrices.jaccard.jaccard'
    - 'iou': 'protoseg.metrices.iou.iou'

  hyperparamopt:
    - optimizer: ['adam', 'rmsprop']
    - loss_function: ['binary_crossentropy', 'mean_squared_error', 'dice_loss', 'categorical_hinge', 'dice_crossentropy']
    - mask_width: [64, 128, 256]
    - mask_height: [64, 128, 256]
    - cnet_levels: [2, 3]
    - cnet_depth: [2, 3, 4]
